window.BND_PETS = [
  {
    id: "hwangchoon",
    name: "黄春",
    member: "TXT",
    animalType: "desktop mascot",
    personality: ["bright", "warm", "playful", "hungry"],
    favoriteItem: "ramyeon bowl",
    favoriteFood: "拉面",
    visualStyle: "2D chibi TXT desktop pet with soft plush styling.",
    bubbleText: ["我要吃拉面!!"],
    voiceLine: "ramyeon-hop",
    animations: {
      idle: "Soft blink and breathing loop.",
      "running-right": "Tiny rightward trot.",
      "running-left": "Tiny leftward trot.",
      waving: "Small friendly wave.",
      jumping: "Short happy hop.",
      failed: "A brief discouraged beat.",
      waiting: "Quiet waiting sway.",
      running: "Busy little work loop.",
      review: "Focused inspection pose."
    },
    theme: { primary: "#fff5d9", secondary: "#f4b64a", accent: "#5e4511" },
    ready: true
  },
  {
    id: "choiyongmeong",
    name: "崔勇萌",
    member: "TXT",
    animalType: "desktop mascot",
    personality: ["loyal", "cheerful", "chatty", "sunny"],
    favoriteItem: "tiny badge",
    favoriteFood: "toast",
    visualStyle: "2D chibi TXT desktop pet with bright friendly styling.",
    bubbleText: ["这天长得真不是闹着玩的"],
    voiceLine: "bright-weather",
    animations: {
      idle: "Gentle blink and sway.",
      "running-right": "Quick rightward run.",
      "running-left": "Quick leftward run.",
      waving: "Happy greeting wave.",
      jumping: "Tiny bright hop.",
      failed: "Small pouty reaction.",
      waiting: "Patient idle pose.",
      running: "Busy sparkle loop.",
      review: "Curious checking pose."
    },
    theme: { primary: "#eaf7ff", secondary: "#7fc8e8", accent: "#174761" },
    ready: true
  },
  {
    id: "bamgeut",
    name: "杋嘻",
    member: "TXT",
    animalType: "desktop mascot",
    personality: ["sleepy", "soft", "calm", "cozy"],
    favoriteItem: "winter blanket",
    favoriteFood: "warm milk",
    visualStyle: "2D chibi TXT desktop pet with cozy sleepy styling.",
    bubbleText: ["正在冬眠中…💤"],
    voiceLine: "winter-nap",
    animations: {
      idle: "Easy breathing and blink loop.",
      "running-right": "Light rightward dash.",
      "running-left": "Light leftward dash.",
      waving: "Warm open wave.",
      jumping: "Lively cheerful hop.",
      failed: "Brief worried beat.",
      waiting: "Soft patient sway.",
      running: "Focused hustle loop.",
      review: "Attentive checking pose."
    },
    theme: { primary: "#f4f0ff", secondary: "#b39be8", accent: "#3f2d67" },
    ready: true
  },
  {
    id: "dagonyang",
    name: "松喵喵",
    member: "TXT",
    animalType: "desktop mascot",
    personality: ["plainspoken", "warm", "gentle", "reliable"],
    favoriteItem: "mini scarf",
    favoriteFood: "rice snack",
    visualStyle: "2D chibi TXT desktop pet with calm cozy styling.",
    bubbleText: ["我就是个老百姓…"],
    voiceLine: "ordinary-day",
    animations: {
      idle: "Cool calm blink loop.",
      "running-right": "Smooth rightward run.",
      "running-left": "Smooth leftward run.",
      waving: "Reserved little wave.",
      jumping: "Compact neat hop.",
      failed: "Quiet discouraged pause.",
      waiting: "Still patient pose.",
      running: "Focused motion loop.",
      review: "Careful inspection pose."
    },
    theme: { primary: "#edf8ef", secondary: "#7ec98a", accent: "#225b32" },
    ready: true
  },
  {
    id: "hhmnyaring",
    name: "哼呀宁",
    member: "TXT",
    animalType: "desktop mascot",
    personality: ["free", "bold", "sweet", "sparkly"],
    favoriteItem: "tiny ribbon",
    favoriteFood: "fruit jelly",
    visualStyle: "2D chibi TXT desktop pet with lively sunny styling.",
    bubbleText: ["想做什么就做什么(‾◡◝)"],
    voiceLine: "free-choice",
    animations: {
      idle: "Soft lively breathing loop.",
      "running-right": "Quick playful run.",
      "running-left": "Quick playful run.",
      waving: "Bright little wave.",
      jumping: "Springy hop.",
      failed: "Small disappointed beat.",
      waiting: "Relaxed waiting sway.",
      running: "Busy energetic loop.",
      review: "Alert checking pose."
    },
    theme: { primary: "#fff0f4", secondary: "#ee8fae", accent: "#6c2742" },
    ready: true
  }
];
